apiVersion: v1
kind: Pod
metadata:
  name: database-pod
  labels:
    app: database-pod
spec:
  containers:
    - name: database
      image: database:latest
      imagePullPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    app: backend-pod
spec:
  containers:
    - name: backend
      image: backend:latest
      imagePullPolicy: Never
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: your_root_password_here
        - name: MYSQL_DATABASE
          value: sakila
        - name: DATABASE_IP
          value: database-port
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: frontend-pod
spec:
  containers:
    - name: frontend
      image: frontend:latest
      imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer
spec:
  selector:
    app: frontend-pod
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: backend-port
spec:
  selector:
    app: backend-pod
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: database-port
spec:
  selector:
    app: database-pod
  ports:
    - port: 3306
      targetPort: 3306